sudo: true
language: java
jdk:
- openjdk8
- openjdk11
cache:
  directories:
  - $HOME/.m2
  - $HOME/.cljs
  - $HOME/.gitlibs
  - .cpcache
install:
- curl -O https://download.clojure.org/install/linux-install-1.10.1.469.sh
- chmod +x linux-install-1.10.1.469.sh
- sudo ./linux-install-1.10.1.469.sh
script:
- make check
- make lint
- make test
